---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: flux-system
spec:
  targetNamespace: authentik
  releaseName: authentik
  storageNamespace: flux-system
  # We install the namespace with the secret
  # install:
  #   createNamespace: false
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: "2023.8.1" # Current as of August 30, 2023
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: authentik
      interval: 12h
  # Quite a refactor three months ago: https://github.com/goauthentik/helm/pull/163
  # https://artifacthub.io/packages/helm/goauthentik/authentik#values
  # # -- see configuration options at https://goauthentik.io/docs/installation/configuration/
  #  postgresql-password: A
  #  postgresql-postgres-password: B
  values:
    # https://github.com/goauthentik/helm/blob/c51952b024451ee90fc3603fae24f39472b1b197/charts/authentik/templates/server-deployment.yaml#L77
    # https://github.com/goauthentik/helm/blob/c51952b024451ee90fc3603fae24f39472b1b197/charts/authentik/templates/worker-deployment.yaml#L80
    envValueFrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik-env
          key: AUTHENTIK_SECRET_KEY
      AUTHENTIK_BOOTSTRAP_PASSWORD:
        secretKeyRef:
          name: authentik-env
          key: AUTHENTIK_BOOTSTRAP_PASSWORD
      AUTHENTIK_BOOTSTRAP_TOKEN:
        secretKeyRef:
          name: authentik-env
          key: AUTHENTIK_BOOTSTRAP_TOKEN
      POSTGRES_PASSWORD:
        secretKeyRef:
          name: authentik-postgresql
          key: postgresql-password
    env:
      # Set the email address for the default akadmin user.
      # https://goauthentik.io/docs/installation/automated-install#authentik_bootstrap_email
      AUTHENTIK_BOOTSTRAP_EMAIL: uk@ii.coop
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      # https://goauthentik.io/integrations/services/powerdns-admin/
    # While this works, I wantted to be more exlplicit, so we moved to envValueFrom above
    # envFrom:
    #   # We may need the cm to exist beforehand, we don't really need it so disabling for now
    #   # configMapRef:
    #   #   name: authentik-env
    #   - secretRef:
    #       name: authentik-env
    authentik:
      # Debugging
      log_level: trace
      error_reporting:
        enabled: true
      # secret_key: "BJRl0HKI7i3T0XZOQiBYm9kDsx9WgzhaeiDAyyAq753MudVlcJ"
      # postgresql:
      #   password: "/erJXa5usdMmtWoR3/rbmhjWNjg1/neSpjn2E8ipme0/znHP"
      # Let's figure a way to store this better
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.io, and is fully opt-in
    ingress:
      ingressClassName: "nginx"
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-http01"
      tls:
        - secretName: authentik-tls
          hosts:
            - ${AUTHENTIK_INGRESS_HOST:=auth.company.com}
      hosts:
        - host: ${AUTHENTIK_INGRESS_HOST:=auth.company.com}
          paths:
            - path: "/"
              pathType: Prefix
    postgresql:
      enabled: true
      # auth:
      #   existingSecret: authentik-env
      #   secretKeys:
      #     adminPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
      #     userPasswordKey: AUTHENTIK_POSTGRESQL__PASSWORD
    redis:
      enabled: true
