apiVersion: v1
data:
    cloudnative.nz: ENC[AES256_GCM,data:mEGwi/ygMkpb40JACQFmN/rIFWq6HEeupNDmxpQSlrFF/z44TCF4DiOFkGzxxC8TLwDQF/QIaazMJjcZWqNJbKI+X7L+W/PUzElJgOvV/bRCrjWcMYw0RizQM0Ez7XtJdS9D6zpbh49NG/XIjqoKHdJUoIg7b+D+,iv:A1GBSycB5xLOINTOL8OEguVwbD6ihRTMoS9pQalngTE=,tag:i+dUB0FSADBVSb2xzdAPUA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rfc2136
    namespace: external-dns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-17T18:55:39Z"
    mac: ENC[AES256_GCM,data:LjIdx0lUstsyHF+OSc6JA+KBzGXxty3JC/KSBxegSKiVlVlGZzsUTPh46K5jwOXCZS4lX2VrPo8QNym16ffG2lbFcR0yS9Kf9Wnddht2FDavmLfeUkySNx0gCZRGekOvZueZm1QMHE6SXtch/ONbWj7rqmCrJ5jQQ7UP9rsw1cs=,iv:tb8oR3StPKHiTHV8cOVb3rpVXFldKPIxaKRL8x2WVSw=,tag:sWdl88+EnaqOiz14GGuZ/g==,type:str]
    pgp:
        - created_at: "2023-07-17T18:55:38Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA49XIfjlxQyVAQ/+JOQwDsic+SiZtWPwrW4ga5DzvxbPM6mx2oHE+95TQEIh
            xE8S4BGAWSh79fyhnu7McUgDZOAqes1VQEoA144efQr3TeM09NDDeNs0s++j9qDj
            i82UIor3lUKO0g/Wcpq0WTpK9SdseGtczeVb09N5gyBN2OmQjMP4YcEBHHqmGouD
            N1etfBi5Dje/6If49arvlFOmJkoO+9T9O25AsVJvRT0sOq0BD8o5bSYWrTQElRub
            0MpA752ZoE+Cm+WAlSyQie0WoL7ToFljCz5DpV+zKsdyuE8oIHP/WBEBItt6HlFD
            LmvFvA6v9LtypYO6e3uE+SjAKF0A2pKClxXy5uwI106ygIBITbz2UuPHm1MImDzK
            tGBJSj3Yay74cnTpX7an+zHH48212/j/wqXR1nh92acL9rT5n/WNSueJponvyxVY
            +jIM8lpLb9gwOm/yDifwLCxEZAWNb00TVd48A6S8TAHBd1IlMUkZRBEtPxAVvziD
            vMUkhqPaUPOO5r+nrbM+c6hj3T1icXfc285RkP5JWAotrfHIAFIpGn/LRZhGNbzb
            V6volLJCLAbWRnnLa3grFcwDQQONC1vC16h0Q5d5V3YQmy39fJ3U9v8j2VCuPVyC
            z09FYFvtYNm3HFhcKHxPyNiIf7XrrqMOEpPeOLQLrT2/BAJkWsGhWxWwIo8IoOzU
            aAEJAhCikv63xQhqq107ZaExp2ssMI2j8DA6AXWHl86N6AHx37+qHPja8Zf44Tx7
            1g12ryVFvkfmW66Dr9J6IAe9N2Aj2AB2x9DgOkTxekWsUOuU8iO7cQ4cj3ClB6Ht
            V3D4leY0/zmI
            =/kdO
            -----END PGP MESSAGE-----
          fp: 7753811D61BD7B2F83C55F3299211032AFAC5FD8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
