---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 24h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.4.2" # Current as of June 15 2023
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
      interval: 12h
  # values:
