apiVersion: v1
kind: Config
current-context: auditsink-context
clusters:
  - name: auditsink-cluster
    cluster:
      server: http://10.96.96.96:9900/events
contexts:
  - context:
      user: ""
      cluster: auditsink-cluster
    name: auditsink-context
users: []
preferences: {}
