---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
# https://fluxcd.io/flux/components/helm/helmreleases/#specification
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  install:
    createNamespace: true
  storageNamespace: flux-system
  maxHistory: 10
  interval: 30m
  # dependsOn:
  #   - name: ingress-nginx
  chart:
    spec:
      chart: cert-manager
      version: "v1.12.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      interval: 12h
  # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  values:
    installCRDs: true
  # valuesFrom:
