apiVersion: v1
data:
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:lxtqsECFPRjNv5DIF+Xh7Q==,iv:6X8zoQnT1c9d08dY0RUUtB9HrjXrTWmB+QkuCrk+80Q=,tag:iC1/nOF3By8wFynkCS4BPA==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:zTc7Skwr67Z3Psxr1f73QDry/gdaH0YgzyN+OU/9SBtALYCFATTefJ0ARNsRL1Tjrtok82Otmp/e5HdYRtEVYieRsuI=,iv:Xa/EbJJBW+gb/kjCUOau9hzXk6BFDcmr1pfw2B1AyGs=,tag:2iAKkfqIKdWgVE86KclAEg==,type:str]
    ENV_SECRET: ENC[AES256_GCM,data:MwqsEqj6kUT+0vfm3nz2xg==,iv:WTG6x8T52f+JLiUQcVRgD0/FYSz1trbjKP/baUIf00Y=,tag:1TWunPRqhNjjmxtAMUd+yA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: authentik-env
    namespace: authentik
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-20T17:05:53Z"
    mac: ENC[AES256_GCM,data:CuOeQ0qkbC6cHL4Mx9P/N2QD91Q9HXOREHMHFehgaZe0sH2+mKb7LyncL41RH9nZeoOzocNuxeuJKLo+RblVCUYWolLi/WL3aYTQA25ICMrarcplv+zDh49scWRY/AK7ZdNQdiQgpLs+nAJKJ2eF4QafyQ0bOJ3TBTI+b9bd8Us=,iv:Bj+nZwQadWGxqiehk+nEhinYhW3tgK+gK8sZjSd2vds=,tag:eIjdpVhA/XkSsXEbklEKig==,type:str]
    pgp:
        - created_at: "2023-08-20T17:05:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1CUw1M+w4b+AQ//TP6+ZrPcAT80AGg9I9wtuO6Va7F6ez/+K5YTQyUcGjTM
            KOHuS1IC9sdlWD8B2HA7zy6jJd7bG8ozNNWar+MGmQF6DAf5XOB+d6QLqSqCY2u5
            Q/N/6n5MNbGU+Jlz9BNJ9uN7pnHH22vzicmD53DcE/EGH0vx1qHfzgyDBxN5WWV+
            Zm2k4dE8YvrSrTsC3G7HE4L5t2qmOp4A1F1Zw/pGbROyqlUB+vW9L9Ed3IbNrmMd
            uTaBjcILCstk7zXbsZnFSRyne9SOfsyfVNOf86Maavw0ZSAoZGPQr8pckwBNCaIP
            jgHr0KjzGy9Q8hagKs14901KqL8+AIHPKLPZKJdlPAxPcuuvvnB1KQi7L8OUZLK7
            0491zhZNplEhlBmEBfsIBrHqSi2uyBkxZytHfDgV/LwlnKQNO0M+wdKxbWp3LIha
            +GktZ/azE53Mbp5hf479ZuVYOnWNpf2GAU8EG3rS00/wEmihEZq4kj/rsXxrOBhH
            HYsrkEuD73morZlfdspsufanHoSiNtmgdLtAmWFLB66zAw/7u4ynTE53OV9ErYL6
            UO2RGI5AM1ddLigD5xM3w7KTRo7i6y5kuvnitBDj0DdGMZW+fNNw4w9y0FVH8sUO
            Erbg2yt87I80rfxp2Nb6KoK7fCD2B0WjWOLrb6s/XnBlHSrxt5sAV4rb3OsfQAzU
            aAEJAhBDiL4xPvrieT98Iwk/4lMc9Rj/mNEBR2IHkANZLxBC2VTUePbD5nLLpwOi
            BjLqsosw40Ph7Q14HSEv3bHmalp6rLpplO24WIvgvAvk3OzbltMzf26ojvtAl+11
            rZQ00MXDvSX7
            =7qUM
            -----END PGP MESSAGE-----
          fp: ECD5E68E3550DD7990346DBE2905C53630D2C990
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
