apiVersion: v1
data:
    CODER_GITAUTH_0_CLIENT_ID: ENC[AES256_GCM,data:V29g/UjEyI601NO/wAaWlK0Q6XFJN1DEkDAz4w==,iv:qbCDz4IilpyG/2nMWxq5DmSvSDMCyzl8uyxzd0gsecA=,tag:LMdy+i6W2DNhUM3VKsD79A==,type:str]
    CODER_GITAUTH_0_CLIENT_SECRET: ENC[AES256_GCM,data:r9XHCjs6pOy6dNNh+QXgmN3kCDmOALAguDXrhBVir2p7uTG9t6rIAk9c0Q7YzE6I9i23hySWCCA=,iv:tdbSVC7dhKTnHWnAogTfp5neIGa/OA4CSYbB3usI0hQ=,tag:l1TBJpgQJkKrkwB23/glfA==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:fj84ZELpdOmbLqXGD+eovm7kJRGjVj6ixba1oA==,iv:34ERFCixlsUyV6HTxiKn8EIJ6QSTE6Ng+ziOQbp9ILU=,tag:YlfEX/d4acNCTSxwkIZIxg==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:50Udq0jP+u2+BaVqNUCARTmRIqkF9bIjvNPXgXkC05FjcmMsGgMzyz7MZE0RHBylxvLGtL7n4xA=,iv:ZrKwxafN0Gqw02///FwH6Uj7BdxtDisFIOH9a0AAm+A=,tag:aeBOqRUffvn87dW/3QQ3oA==,type:str]
    CODER_OIDC_CLIENT_ID: ""
    CODER_OIDC_CLIENT_SECRET: ""
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:rqJXYwapD4rjsXlkfBfIrBC9pSqn8+BPjwcoB5gkzPZ2NQZL7rBPZ1vMghkKtXMA0gt1FspikvKI2LNVRt2GrCOqjrHvwKzJ75449nxwiD5MkI1DutWducG4s2JDIO9YSFvKFNLRY7j/dFDVdmvUMJPK3D1/+e3gG7jJkr44mapOl8z5Shc3xGk2//c=,iv:CfYJIrWO8dxXnEXB278AgPMVLxIr2Tdph4MWxvFIPUk=,tag:vwixf+0b11ka6/2aSG2C1w==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:RmRTsq8sBtear5jzIRL+PB7UPKjQf9IF+82LQgDoMh2e3Tx/j55uqfKIsIR45mlWw1b39zaK6GAuZ1KKHwikX+KxJMxTb2KXktW+F3nKCdS9bdt1nxVN5uI+lHM2SfHs5kjx3GlygVhQxEmNxHKj0U00LmqzZedTV/Lzrg==,iv:gBNyTqhVM7rYOiQhu23+ROhMua/mgs8FK9x0WRzzmzk=,tag:NpMHoshq+37wg5xhP63puA==,type:str]
    METAL_AUTH_TOKEN: ENC[AES256_GCM,data:BE2RFhFojKDQd2LFgCmx/PdZhuwcotTBx+5GVpQVqVOxfCEo4tUXSpQ8Nvc=,iv:W0duIYsYpFoVaMWrSY1wjicSQCfawLGi62ZKpZy1MP8=,tag:dmVAVa8eVGPfhbRChlTPkQ==,type:str]
    PDNS_API_KEY: ENC[AES256_GCM,data:RjIafUsbmD1J2Jzf,iv:MgyIQG1i9jq0vH2OnsfHNp7mYDfTvo1YBfgCEQguF74=,tag:9pjmimSxkFOsIOrPcgZP5w==,type:str]
    PDNS_TSIG_KEY: ENC[AES256_GCM,data:1P4TzvWvA3TUpMlC3niOCLbT7wQzBUjsAF4XBykoEqtpsv/P30G/ViASAC7WqNrKvsfJKDO9axXtOp1ZJFeQo78kKDQWxenfHVgoxHRQWcdmHBXCJtkOW28ZsP4GJLxWEWNwko9Mfzmx/Dl4GRFRFFB0ThHK5zc1,iv:BRApP+QDtDOUHqYlbDyoYesWP1ZwGzXAepk4nv4MoHk=,tag:eR1n0k5ofNB8Iwdvcym+XA==,type:str]
    password: ENC[AES256_GCM,data:UsQ7wGoJI+WzxjiiN0f/2Q==,iv:zzRdmuxuuFEs1ztxtZ3JX46vBsij979vMKgtVZhi0vE=,tag:Am40DFHHgywLENs2q5L3mg==,type:str]
    postgres-password: ENC[AES256_GCM,data:+BQO6LcQ2G90qgp8QWYDrg==,iv:T0Wz0O8amvKW+VTO7oEK+KNf6dGdvvmLYPMZz/2uV0A=,tag:FWSMx6gXMftPihVwjilunQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-21T10:52:58Z"
    mac: ENC[AES256_GCM,data:LVP2QeOYAKwU73/jEcqTSmzpzchGxjboFezhUKBTG55H7czabk4LHgrLY5osMBmPFbvW99XpNHhIEySN+qkSRw2wUJrNtrJvthqJgB4Fhij3XvJNbbOvJYVa+NnMrAn0gqhieV7NQRi1BM71Gx1/rqv/0kpbzqbbIaq8mQNMbBI=,iv:e3aEhFe5lGI8hF3QNePtSy5PkmFM6lK3vUocVxty4Gw=,tag:hCI2wTgwNr7xHaRKnzYNhw==,type:str]
    pgp:
        - created_at: "2023-08-21T10:52:57Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1CUw1M+w4b+AQ//VdJyW9wlcNPQd1YS08/RH4zBr0t0WVBc7q10gEv1QdHh
            oNlVLyg0NqWryI75C4MAkPJfv1AzPuDBHmM9dCbxZIQymkdQYk07FqGcMd5Uzn/F
            Ht7meh/7jE3SUPLYXpWJRmxse9pLvJjPxPzaB3cplvautIpkUVyAoSGQ5WbANNYe
            VfFJw9ik+sHeVxoFwd0ULK6zwjIr8T37rEJC5bh5QmG3ce3E6SG4/UzRnksfx4jN
            HWriNI/t8zulJNy3HExU3OGtuEmj0UNk714VtQp5PaRvbm85V24tpamFLf25r7wZ
            rS5vwQqMA8exDQfNmYM6nCLpyavBRcK36T3AQn4vECn8gIv6ZwLeglkHsPKBXJRC
            QShvq8HmjZGeVcMxnTp4w+DsGTzuVypul49BaCXPmIc8pQk84hCcp/8xS6VIeY84
            B/1KCewhOQBEMdurMTi+xXXYHk9wQO2/YMj5WYjs/2c8vcpMywAORmvQ4Gbn+Klm
            URvFpygu5sa/reHUCTv9WE3nNXLk30QNepsUH9y8pvLpAK9rOgZQ5YY3lPZnmymL
            je4CsRKvX3t+0nSN8V/ocs+KbL6JWQ7VWyT4Xg0vYFhPB4tz6b7tH9IAKcrrEnYP
            nVysYfPamuG4cSAzzIf9NakqZgd4WHuGvBF6609suMS+cKLwPj1ZbVVcEJAMsSfU
            aAEJAhBtC9ezyyhpHXSvlfSKduB7iCCna/vKVIBlSEmZcA692F3JRPKJoxlRnZus
            nraBDrsRCM1xTZhaZEWE8nuDcZ3WZKsQV+aLH9lgATQTLomQ3+SA0/0zaK2uiI23
            fewv6jDc+A8Y
            =yFJ1
            -----END PGP MESSAGE-----
          fp: ECD5E68E3550DD7990346DBE2905C53630D2C990
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
