apiVersion: v1
data:
    AWS_ACCESS_ACCESS_KEY: ENC[AES256_GCM,data:IRhU6iFOj0fuOXidLVWvGQ==,iv:DQbnJwMjcf31kSZDg1lPEQJo4hJ503Vyj6YB+RQLd9c=,tag:Q/2NzV4O9I2mpt4AS6NYoQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:O1npZTqeNFQ=,iv:kzgdA7X+NewYs6ugACHGSwNgrtwuVhRSO8CRdKe/m18=,tag:cC5/Y3Q2xM3cre4/TSpR4Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:sGHxZPn29MBIxkt1F9u5BpVztDu1BifIUSUImn8d/Hd6ZOx3l8t9+g==,iv:l99JjlMTz7oUu87XI+FgZl+cMEmX+ukv0i7DL5tfI7o=,tag:az6qfV+VmY2IZEJvC6VKWA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: longhorn-minio
    namespace: longhorn
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-23T09:34:29Z"
    mac: ENC[AES256_GCM,data:AeXKZ7pRHB4U6emUq+QxZUixqxlB4hT79i7Flt2As4ULc84q76mi9cknMpkX2UlGiZVDtakIEUldVgy/jSiEXavsFhThky/BpM4nymm/8RDZlbSX9l57O54YRQqZmtaiLMRM2cc6zj/q6snsvzY83vJdQOCwX67DI7ouFpZ7G4w=,iv:f7HiTQFSDiyn1P6/Ijxy29e7uOszD9u16S2q+Q+/fwk=,tag:a//PoYKjwE8xVNXVc4jVlw==,type:str]
    pgp:
        - created_at: "2023-08-23T09:34:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1CUw1M+w4b+ARAAv8WkCf0ciwlxY78bJY3y3wv2OK8Ch833orPwNuPFjtQ1
            ROqmBH38M7IlPPtqDbI3uoIK8Ipl4wMxq8oYGZFfeSFGttW0KBknH5WtgINBMz08
            7Z1uMux1znkRK/J0ZNPIg12xdubduinyAVoLCGRmxTlewhA7fPM1qv/V1lIWOcJW
            FKdt0XakSicggG1vtz9TFXzMsM56qE35yc+AUNmFcXsVg5lxumSucYPNBqTPiXgW
            Cn5e74y09wvowa1u78oQfHjDkIDp5mOMU4NPSciMfWk97JAZzSL/Gd0HVlzFzbns
            hCSPRgtFlA8Iq1ISMCupx0kaVIuuUjL8+n8sxeLLxgUZ5p1f5EXex9Fs3ghwYJSY
            x/8bsqmoE3bls6eMs1JRWZ9IaI86XtpTTP13LuPJVPe6gPPc9u88oMWeQ2EiBTd8
            UFZpjrsB6BTWdmhisH/g9k1lVUM3bu31qfdK6DaxAlCiaxFv55Y+IC0/bDVLKnOu
            ZfdUsL/gXG+FA+lATZPdJNCJbnyUD/r+1clCOdvdFxelLG7yaPcwL8mUjEe71V4a
            xBfgLqWvvc15nbZj6OkDTdqstDKA5VbCvp7KKPe1tQPVgl2HuiZuWHrYWpi9Ql7G
            VoqvvSxOu02UHVgEFvOJ9XlP64ZPQ13SE4RcUI0LOPiiSl153rKLwH53gpc4ul3U
            aAEJAhAR25KPjgYpLmE6IEpyZxTLSPKo1kFAYJa+kaIZ8Mnza1gnHG/SHdcJjfI4
            W0Y+L/cHanswa5s62MY58c0yesUlVk4bD0SdpTkFRLI88a9wvzUcOYj8FxTsrNDl
            Dhzx9Zh77dwr
            =qKWh
            -----END PGP MESSAGE-----
          fp: ECD5E68E3550DD7990346DBE2905C53630D2C990
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
