apiVersion: v1
data:
    _api.conf: ENC[AES256_GCM,data:c4/5XspJLADZhr6ylhtQ5trhBo+e2T1RZVfKhxNFYG7bkDRLb6XuZlOi4Kp1uhXl+Oq9s18SnW4UAHbAY6/lvxN4fuh7vVWytDgnqcB3GA2CTbYA36LpUefJvaT/26+ptJJYIrU+5bX5Mk+6DsqVpxELy3BIhZ+oRZtD9IARnraxts9y1h8CoBJKRc5Bp4J/GvZte5apAY/NSZPM,iv:2OAKAFsXOivpIYk+7/v89mdwoz3JEnE3VGIA3gmCG0M=,tag:+pi91gyT1uLtgG6W/WuZHQ==,type:str]
    admin_password: ""
    admin_user: ""
    api_key: ENC[AES256_GCM,data:fp5Z+GInPf70usDq,iv:EPD7CZim7RLc5mN8VGHfJ24RU0V7QdstTFAO3cZA+NQ=,tag:hSbvlDenW+kCGIQjfBEuPA==,type:str]
    pdns.conf: ENC[AES256_GCM,data:9mqebr1C7N61hpq3rB4eMzpu5DBETlbprpb0v62OKmfQ+CG0ffYUelZrsHF7Uuu+bu9H8ORx3bSTXCTX35IBp9S6GQ9va7UJNp656/VwZ1NmypL3ypDrBqkNKLZ0HWtXm7Kysb1GzeSw5mxTefr/gtbq8nMF7pCGXKVjwWh4Hzg9uita+3IWa0q8NJRfS3L3LLG7ugp7WJq6yv8Oo09V3c6fh3YPDJeAI/GZW/QoYfVZRP/qX7EoO+p9gijp9HjsC+TwFrrEY8BP0TmDT85Lj4UnoybTPzROtwUSvN/snyAn77P8fkPPmVE3ag1A8OmID9uXbOLULauxXZaK5hspdsS/xF8/UbZzvlt6IIDeBfzRp4iclZMFlvh2R0OIowBPx+oODM8N5z6MzDHvVisrjUVjTp/Ppl7xe8zOUo6tDoxMXFR0VKp5Tmr+7y62DdoNkl0/JYihoN08Y6f++ScUIdg+XBq2jSxNyFR6r5qpWLKXRmvlh9Zjn+/PgZv+nRPS/tEb3yhPZctZyFzZfo3qiFqj1AOzbkxT6v89RCQ+FHwW06owBaTixBSPzhMvwfaFfoKPEZfzJMM7skrLOHbrsQffznlbZZgzsZZ3CsAlrae7TitiYGENtTz+Bmn4aQmi7xykjLhvZWEAoAhWl2fRmliunpSkvXPqFdaUq7HaAQ89aYFbE+1YNIf1OElsl45jzky2ZBYmDa2gvMPDtSh2TqZdFAo9/Co6E833qG9Oy/0Y9P/nk5wIqwQ59rvnSaiLoDbe6AT//fb4juwRPlbK95PQJr0SLStYj4jUtS5NFTQ6swGv9dEYzMDXSUnnLsdgXN8W533Tc6Yd4kxjeM2z4E/EShIovRlRZJ3jNjPV15C5T2t49mvLVtMZf9K114Lj8wRukRGhhlMWzeBYSKguxNCyGb1xtfdLIdBkpJGjrbGXaHYL66LOqMudnr9HfxgiuiMRIwBh148gsoDrUC9xWKlrxKobX2P6OP0tsWi8uT0rcnYJoGiSmtSH739ZgmSiIKUnhKGI184JeEfQv88X05LqQ+BEsonNEgb/4A==,iv:o9klNFOcHLwmqn0O1Ggvbvh0ZWOSr0P86+WGNvyQ05M=,tag:eIdHBL8hYOr+Vp6XiFw3zA==,type:str]
    postgres-password: ENC[AES256_GCM,data:goIo1ELnHuc4DCKxKyPlmg==,iv:rF3uCEM5VtF2HQvBQSBFt1sz3h5rojHuVFfxUFmsCMc=,tag:1DMtqoWskZM+/qNfBvqB+A==,type:str]
    postgres_password: ENC[AES256_GCM,data:jmhWXLOzYuHGRrqtNHwbfQ==,iv:yl9NY81NIpHcUPMxxqXlHCWV93MurcoX4mWpR8j7Aqc=,tag:wv7cFdWX7IzAO+FGmNh7qA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: powerdns
    namespace: powerdns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-17T19:45:30Z"
    mac: ENC[AES256_GCM,data:8/JGzz0Kvfv6VVjil0ZwhUA97nK8MIX1vCkd5lOxJ2ZJeXgdxCpdSyILNBJ1EqDA0JyEFM5s8jg71jjWufhin0P2NxjKOUlOeKNxcG3j4DqiuGCgPGL80ciTOlyMHRqEzyMa1kgiuuLE7KMfElXW+knQ5kJXRkdQ4gj9tImN7n8=,iv:CvA/6rPf1+VS1inwDB1ezo3jw+rgknGxKSkYx7jbobY=,tag:qjf/taTvWIpLUEacdRXA9g==,type:str]
    pgp:
        - created_at: "2023-08-17T19:45:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1CUw1M+w4b+ARAAu+225u2F3Ba/zByeqcXT3NOBxACqOLuc+Gx7HFbSd7Bu
            uC7JbuV3zIcGoI+sfDzBriYVzP/fqf/Wk+QkHhgJSfOGnyMWDuWh517Pj7phm5DU
            rDdqPzWjaT686oA9diwBQKqjurNYIgQrOLdB0uFab2EvqPpRjUNEvxsflrDlt9uw
            mlxhgTva04oSeJzQ2jyDx9acH8z63ZoLyotF5UUjAcFWeAfFtx94nXnQeyPGqjBW
            2K8wDRT39mDaHo6qr1vzf1HWgU2VhSp7i0pn5sQKSdI/J3H3hUrTlCk4v7BtQdID
            axgaheagqtyABKpKWkeZ1JYYewodXGSAYWFkSlpJX9sbBYnxkzBoD0Yl6FwsXM0K
            SaZQ5cHQEKaRZp+NrKjPp6Q477+KCLbzZc94J1lIaYcDYU6s4vX4PyPySWWYGx1I
            pwGDrrtGbXCEafSIbNXMsaD+WcWtuMn/vklwmThN/cJX/k4SVNCpx3+Cyl/CAFsQ
            SonYukzQPLbqdDmQQ59KA773G0DM4HFl2AQxZWr+Y5xbUEcJJncg9H/QcDMD82us
            h7d+kHiEmzs7cKviVRzP8qwXCbFNLTOy2a01AXt0EU+3R+yrtBvCFbqQQg5mGnY1
            PPyqppQEoPNeW6TnMLE2Cfugym9EHjD/TX5VRR5bl/UCZJOU13nzxR13MdEY9WnU
            aAEJAhA5Y7urZStyPx6FGDVUW35PAlc1PLc2Cdf0LBq7M03KOGU4jG6XiJ8AG0Uz
            kd/dK7cCfsOwKxaZkYBztc+4yLjBxL7TzsKqKHVCsW59i2XL7ZJIYjHCoitK3ufM
            ubKXaf165dTo
            =Gnnq
            -----END PGP MESSAGE-----
          fp: ECD5E68E3550DD7990346DBE2905C53630D2C990
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
