apiVersion: v1
data:
  _api.j2: |
    webserver
    api
    api-key={{ PDNS_AUTH_API_KEY }}
    webserver-address=0.0.0.0
    webserver-allow-from=0.0.0.0/0
    webserver-password={{ PDNS_AUTH_API_KEY }}
  dnsupdate.j2: |
    dnsupdate=yes
    allow-dnsupdate-from=0.0.0.0/0
  gpsql.j2: |
    launch=gpgsql
    gpgsql-dnssec={{ PDNS_gpsql_dnssec }}
    gpgsql-host={{ PDNS_gpsql_host }}
    gpgsql-dbname={{ PDNS_gpsql_dbname }}
    gpgsql-user={{ PDNS_gpsql_user }}
    gpgsql-password={{ PDNS_gpsql_password }}
  pdns.conf: |
    local-address=0.0.0.0,::
    include-dir=/etc/powerdns/pdns.d
  soa-content.j2: |
    default-soa-content=ns.{{ PRIMARY_DOMAIN }} hostmaster.{{ PRIMARY_DOMAIN }} 0 10800 3600 604800 3600
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: jinja-templates
  namespace: powerdns
