---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "v1.12.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
      interval: 12h
  values:
    installCRDs: true
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-webhook-powerdns
  namespace: cert-manager
spec:
  interval: 24h
  url: https://lordofsystem.github.io/cert-manager-webhook-powerdns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-powerdns
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-powerdns
      version: "0.1.8"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-powerdns
        namespace: cert-manager
      interval: 12h
  values:
    groupName: sharing.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: sharing.io@ii.coop # REPLACE THIS WITH YOUR EMAIL!!!

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    solvers:
      - dns01:
          webhook:
            # This group needs to be configured when installing the helm package, otherwise the webhook won't have permission to create an ACME challenge for this API group.
            groupName: cloudnative.nz
            solverName: pdns
            config:
              host: https://pdns.ii.nz
              apiKeySecretRef:
                name: pdns
                key: key
              ttl: 60
              timeout: 30
              allowed-zones:
                - cloudnative.nz.
              # zone: sharing.io # (Optional): When not provided the Zone will obtained by cert-manager's ResolvedZone
              # zoneName: sharing.io.
              # apiUrl: https://pdns.ii.nz

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: sharing.io@ii.coop # REPLACE THIS WITH YOUR EMAIL!!!

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt

    solvers:
      - dns01:
          webhook:
            # This group needs to be configured when installing the helm package, otherwise the webhook won't have permission to create an ACME challenge for this API group.
            groupName: cloudnative.nz
            solverName: pdns
            config:
              host: https://pdns.ii.nz
              apiKeySecretRef:
                name: pdns
                key: key
              ttl: 60
              timeout: 30
              allowed-zones:
                - cloudnative.nz.
              # zone: sharing.io # (Optional): When not provided the Zone will obtained by cert-manager's ResolvedZone
              # zoneName: sharing.io.
              # apiUrl: https://pdns.ii.nz
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cloudnative-nz
  namespace: default
spec:
  secretName: wildcard-tls
  dnsNames:
    - "cloudnative.nz"
    - "*.cloudnative.nz"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
