---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-webhook-powerdns
  namespace: cert-manager
spec:
  interval: 24h
  url: https://lordofsystem.github.io/cert-manager-webhook-powerdns
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-powerdns
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager-webhook-powerdns
      version: "0.1.8"
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-powerdns
        namespace: cert-manager
      interval: 12h
  values:
    groupName: cloudnative.nz
