apiVersion: v1
data:
    CODER_GITAUTH_0_CLIENT_ID: ENC[AES256_GCM,data:rtHlUy3tvw36WdOs8c4XjE05A4C29mhaa6qK+A==,iv:T5SivfbQKjQdMj3W1Du1vg6byFK90Re+2iWiSZqVoK4=,tag:31L6yMIQvFwKgBabckWGPA==,type:str]
    CODER_GITAUTH_0_CLIENT_SECRET: ENC[AES256_GCM,data:67jxweTiH6fOr8vlSeygJN18qkX18pcMZlCd9PXcb7BfSUGPsUzZVKS5lnpFnYv7FNIUKUNA+ZI=,iv:bSVBD11BbFtLGoFr0KXqQHjxVbnNpOv/2eaboTgHg/c=,tag:H34TdaZSfYT1IYAC1mlbbA==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:PRN3DR9NKcU4NCEk1bwimCuxHjnZUtTfHPnOKA==,iv:DvVEx1HKPTpjYPOoPGcwp8DJxwA/VNI2Kq2qMf5wHV4=,tag:HHOFeeA6SuBVyvXkA7Jidw==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:jpE2as5yooZzJIqxLiSLiQVOGFxjk7eU8TRy41/OVeQRdwS2PhJ16luRWF9trbOw2s0Vf8vSmZg=,iv:v7pCIEIFDUODrHgp8e3xehOio96e0n8w/b4ZO+ItP8A=,tag:bmOYgI6Z6yz8UsMyqDRDCg==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:Nl2vgSoK+ATCfPCgQ1DOai5xDHLEdDHfs6K6zibWLD5Af8eCdI9wXm/ssx3V4xfI+Kdd7LrcAY8=,iv:At8QvWNBtYxZCBZYXn+OibPSvS1es64SMx0iC6HtGOc=,tag:VtDyzjNXYFOGjE4bC47GhA==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:CdJwsWKUbahm9R+53FUEHHLnn94B4fH2x9pLOQFb1/HFiVprB2FkCttELhfvrb2YsfF5IN/Hm4oKMpVq5G1gtYlw5gQbyUNf48UMcvpEh5DnUHZDFlN4ZYWHYTEgE1bmf9y2FHYP6PSFEeDsd+latchI02kWCv2Y+d+k3IhWfxg8YAP2QwTeXfgzt5pX8QFrEoRwodnJUPep+AUVCXH2OHW8nf/beLLorZgCUg==,iv:pBKfUmrlYNSJ11zB4ZE6OUsf+9mIQuwhfYfICGpAQ94=,tag:y/P3KQpm30CDEL0CnvW4IQ==,type:str]
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:hr5hEb2aLMjOwbPeYmcuZfG/IDQ1Hpp7oT+X/wQWGdr1IqJ/wGNftbDZfhw/nyGlj17cLpENjdWNP+AWS+NC8roDpHkzRsBk+66mu2huCQEEDw7KBgIcrMt6jCIoSq3j+Oh+CHzSy/cPygtUH7G/Xs/LNTGvD93GfAIdTX+RhX86ixl9devh7A==,iv:MFsg2T1kQoqRsHMc+xfCvgwHrQ0s/U0/SPuBb7KY5C4=,tag:RB3NEgErYIb/mq3CeMhaNg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:s2D8ZZoDnI1FGwNLi28fbJTNSb+9PST0CBqm2ZF6GznX41WFCvx0WOVHMxmFf2S7CPZ7BVt+K5eZAjk1hDjwgcYmKlGrCnuOq0O6T1zo369SAyoiGqlyny4edTD9dcjJw0EDGGILXGCT+/O1Vp0d0afODwyULPyhLFIO+w==,iv:ZlppuU5J3PjNQWRwmll2qG5pMo+DwioFelm1pjAQQlU=,tag:JoAE95V2WwKFkm13wHe9GA==,type:str]
    METAL_AUTH_TOKEN: ENC[AES256_GCM,data:ej63FY1/pHxw/3xK9FpoIaq6ByqG4Ygxum9NfL2KbKooQdZz8f8ESQXUfLo=,iv:ZDJNIs+Jyo/54F1bvZBtauigAxG8d53SJJaPiVYVERo=,tag:ProLdV3BRwLcMOF+DGpK0w==,type:str]
    PDNS_API_KEY: ENC[AES256_GCM,data:zdJgUinEgmbAo/Pstyos7U45cJgWzXYdfm//yLz0x3C1KpZlD/cZtsgNVYZZlDr4gBd02U0VbnSlomF3,iv:VZtYRD/iAFGnodVFV0iZohz/up0nDjd9ppIpFfGuFSs=,tag:v0LqSZ7WLk/RM5xPLk7WMw==,type:str]
    password: ENC[AES256_GCM,data:9Qyr5e+XhNBplO/fAprAPw==,iv:EDIBu/jdfzxh/jYr0Hyn/OctmhMDB0KAguFsfZWz1Es=,tag:ukRutH+ZY6nAPWuaZ2njZA==,type:str]
    postgres-password: ENC[AES256_GCM,data:J4U8x7IKszRgwDHB+Xja2g==,iv:cd3mtc9z4xQVDzu5FLG/kr/5hK+Iptl2MPq+O4vuc/I=,tag:lY/FSNIY2ENvna6MMSXPxA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-03T07:37:34Z"
    mac: ENC[AES256_GCM,data:cRb+tkfaH9TNNrNHYObAGcMlNqPrQPYJVVkfVLtHelQoVSpTqjQc6pCrbzXKgeLw4nLzn4JAN38lYP2PdgFZultjTwCXshzeJWhLV8CjCKFRT3CG4NiCUnSNt323UQwlqaBvQf2iQgasH9imMKnMoH0hR09JIKmQm5NVB+rwNVg=,iv:UCSA2pL+svozaMc4Juw13+Ej2eDBbW8ya+l8M9qu5yo=,tag:JXGMMm6CaDM1NttTize2CA==,type:str]
    pgp:
        - created_at: "2023-07-03T07:37:33Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA49XIfjlxQyVARAApx43GyQ/2o3j+qAhhjeJ2uJm1+1+ufS34imxPaOWZwdx
            aVzYkjTzihvnR9MC/DTCu7brF2ht+45Au3g0llfKEpBYC9H61PNAhPS7ON4LCCnp
            967uUEXuAlOpn/2+SIMtMV0bmhwNlNsB8x3HXlUTKylI5r/06ua18SqF6AqbNO2R
            pyn+cxzVMdOfQ3lloFD4Uk8XjwcfCCnQQGquLcRmHrdVrDBQRVvdMRGp7GgUqf3O
            MSVfp/+X0ZevQS6fIrYQIT4fXFQhovcK6e7Tqad4BmfkH5daUbOFHrpc1jVARFXA
            AaWCJILbbGYPdBpB4ZGyRowVbq/kU3fnXGIcI3VGYnzUymWtnbBuJvH13RRyGelR
            mH9Ov7NKOcTXztjcbbONHF4h2qfUKDguD7CiLgX/Sk8X/nlx07OQMjnmiDV3AnAD
            xpzhXKMsIyXxHOqwwnKj5J6P6ocsSYc5OGMZMVK60akUjTz1zA0K7skJrzYDuqEH
            P/l1dkVHJhoySzl66ytEroDjhXCNREVUoxjmdkJ974/UkXLuY4PwcfYdO5ITZ0I0
            q91ty3cIOhI7RyzmBOWiH2NDDIJLrgOvzI0dUpSayyuvrR8ORC/e81eqcvAjYCh8
            XwO/nVkXoK6Q08v8vYB2Uw1Y2C1j0TbJc4C984AoURaXkqIGvLqpnetJyzyQNoHU
            ZgEJAhBcOCgugSYlNRloThOSeSkb+Nw2crbdanPu4aCUAfUC0CtBw6nQNaZU+WWx
            aEOuIFKvxDyxbEaqx2o2EjC419Fmsv6As0zCzQpf9vJiuu8wD73eme3wsjn1JFSh
            JpS+jsf90w==
            =zuR3
            -----END PGP MESSAGE-----
          fp: 7753811D61BD7B2F83C55F3299211032AFAC5FD8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
