apiVersion: v1
data:
    CODER_GITAUTH_0_CLIENT_ID: ENC[AES256_GCM,data:ZF5FIGSaEwZ6LEEL9GZYr2WM7yKaDmJvZoznEw==,iv:5IEdLfp7XSsaFt0zXDKYsg6yENgIYscLrvlYJWskNqs=,tag:o/B8/umgmW/1kZwyEWiIvw==,type:str]
    CODER_GITAUTH_0_CLIENT_SECRET: ENC[AES256_GCM,data:zR5IIIIAcJTwfxdNC7IAQ9p9e9cgtiIRRQKYJnyJyBD6ixumntZxc3dAVPikdPvnaP8aoN9VQSE=,iv:g9YiERKirnxXsgdL1Iz5qqNtU0Ym2JIoHI3ayEo/SVk=,tag:dUR+2US9Wj3SIB+DFiertA==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:9sOiIlPodEj1vLHQsO9B8/EO64zf+w3MsKUxLw==,iv:Il3hXG5JGH65KG+/SGqxrIvrkXBvqo1viZWepkttegw=,tag:o/lGsHpC6oYTIYObMMf7fg==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:CgSMoYfn4Nog55omtJ87aHB0zJLbRv/CAVQzU1hPjOMs47Wei5NvdkstPlp29uoBuUIUv3u+wDc=,iv:WCx1R1R//UGHd1dRAK+L3VSstJN/h9h/dspotGgmIoM=,tag:uHCwEOcLgn1UdiRsZW7ECg==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:P1yCl3PY+jFwvEDkeBoCn35si9qO4GXEM9Jkr2wbp6hKla8BFIukM1PCaB/95JWyoAZY2uV/YQo=,iv:ZefbvjNCKJZJeCe318Pd2jsn1DORBUG3HgyQ8a3bMtU=,tag:TMpKTDzG592yOBYwE+W0oQ==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+85GAHktTxXECG5w/m58tLQeDPAOrxdNfPrTzyKG+N1mZObSV0gx2Qd0emxsfZ/g73ToccA7SdLz/AlTJEZCRh33sU21F9+QP2G1UTl+bN0PEzTNsWnp1ZOYOCMN334KIUQ4w9cPksm0UJd8WQrGLpymi8UfWmSbCus83XUEyxBW7dRw8wdas3NtYinMJnYKzWVFcs/4tMi8t7dlHRBmm4zo8cjZojhDVb+d2g==,iv:brYDJHHb3Lyyb9iSasewUgS6Oiynlws28WTd3WsiU80=,tag:LVpUX4s2sN+j/H42vEGMpg==,type:str]
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:r5KuYma13XxP3innnpQs9xW62gYTmtqIuRBInfAhqi5KpDtx0mgPM1pK4NdKP2sDUiloSWsF2NuBsrT2qOnCskrDnwVHeE2hzGicL6bj8i5+tn14jJzQj2KWdtgweKsTwxAPihz+fN2NtoOt7lb2AuSl+9oD8Cw9SqcCkQbeyIJ9dCfZrjpE6w==,iv:CioZuxCCXszwqQzcXlGLsqhS9sz5K2bmoqTsu4HwSJA=,tag:Th5b9RKD7DKxarCtym3V8A==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:qReFqV2YBC/Hq7/IdDjiudiM/KLSAY1R8+FKdpmqq2dPOZbOU00AxoI8ADmUan7PObx69EIft71yt6H/GrWxwjOxXOIvh/iGddov1y6G5fgPFljcFbEnBlL8XjiRpLQkQlSmmHcREMsuiRV49LnFVLUKkPY3q0pExjKl9A==,iv:TF6XecFkKycO9tycIQzFuWQFfJOTR3x3cUR2KFyI1Ls=,tag:HY1pZYrvw3nHYrXXm7SwYw==,type:str]
    METAL_AUTH_TOKEN: ENC[AES256_GCM,data:1gAIzcjjd2geSSK0z8D+Y+ddsrEay1kWEQoaWUkjfnTCZpz9N0D14L6680Q=,iv:obTGNRtmC/MU2gkHrYa2b6VoSd/k3WYide8lHSwBDQ0=,tag:zuAdJyAWpZ13Sa9Nmfor7w==,type:str]
    PDNS_API_KEY: ENC[AES256_GCM,data:hEbhlDjl98A2HbL6+jeW/0jQ/FLWHQZl+4ELmQ==,iv:hjo+cfSThxwOH1OkIjTsFUl2nsTVGR+OpfK8gEVCi5A=,tag:9AqGNb1HBoorV4oo0RDW0Q==,type:str]
    password: ENC[AES256_GCM,data:jWpm2Q4X6rmgxf0/lc1kKQ==,iv:MS87kFyFo4rGMEBYkFDbtLDoqIz59dhcxd7Et4mmnQg=,tag:dq+0nD2jlKI1LyRuycr7VA==,type:str]
    postgres-password: ENC[AES256_GCM,data:4wN/2X+AkYuUsSF6VLliag==,iv:gfpUhMsrvxo6UdJyD5rPAt5atjNrB5pqt608Lo9mFwY=,tag:hOsVi3ScTQIhBE2UNXIJyg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-06-30T10:51:12Z"
    mac: ENC[AES256_GCM,data:nqdpQlfPgnoAevh116vGVZTAJRgNAA781ZyJ/4xGEkJ4tV3RhxHpyZ7BOb4+QaabONtNqUngZHG/pwPLkGFyNeepBUNFzQjRZR80/ZV/7gH0aP1SxzjeBvQU1ysdOY95giQYtCKOjc5UnJ3VLl6DCauCGLXqFBmF+cp1SFTtb4c=,iv:OaoBLPgRc+yxWr7ltpcB5VhTCUPXjFF/vAj9cMrFhkA=,tag:6GhOIBRloOHtPA3bvdoMKA==,type:str]
    pgp:
        - created_at: "2023-06-30T10:51:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA49XIfjlxQyVAQ//fWGrnYN+mYVSO6aGkVV1Agg1Hb0Fdp+XrkH6e/ZO2i8z
            mN/VQ21RVUaAfiHxXLR+CsoTkkdnalZR4aBswJTmwPuyDfEsQUDz8wDVpVACV0Du
            cN8hF6Jp3VC6yfeoCRfPQYbw8E9/sAYD3PZIMNN//OPn8wSgxSthFC2FojnZyuZd
            AlMFOk3go6yRaxG9KJck+PCWfPvBSMUIuOu80Vo6qqyKnQ7kIiuvKFeQmD9w1JFX
            nUj5Ezu+cahpW0hAmdkPpfNgOQFQ6WnMOSBGDPdYYgcoVvQEgQ1EQzaKPWXynPR7
            TY08gFTvDRuYwytRkXH6o+JiQB/a3sVorAew58IycSux0YvgaRFhbqHXpqVFJD9e
            GBBWGTh7Dx/fc2GHZZ2zt7bhDete3Wu13yyIfkyJ2S1ocT481GW1Cg9SchYu5Xhd
            S50iz83MNSnStY0KfaBcQklCrqTGZcHaSSNp/z95P5kAlVkPKswmuOa94oH2XbTt
            cRZb4Tww6dRJC1HpU2QsgNK38L1z+MbHXKbKoKJDsP17tinMb2BIB578wigZxlYI
            tH+3dBikz2kLNyMgnZibiNyTnUyXWyH7BmicGtyHOvCpdabh7sUpGkxK2iHlVHtd
            TjShqJkVSVOZlZgnGn5YpsMfaSJRr6LwQMo1g7wiDMJI4fg/oq9S1PqQbeaQGIDU
            ZgEJAhDPw78ZN3uXio6f1w5VowBqgGZKc25kdhUdTVB88jT+Q+Y944sGTVJU1Ejl
            rC3xX6RLl/l8kljPfxrnG4oiCogTDh+LzDSd3ZdIdgP9sml4njkwk3hHwUG491Wb
            eYRiLasqyQ==
            =NCOu
            -----END PGP MESSAGE-----
          fp: 7753811D61BD7B2F83C55F3299211032AFAC5FD8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
