apiVersion: v1
data:
    CODER_GITAUTH_0_CLIENT_ID: ENC[AES256_GCM,data:pqXWZuMe7LVOY6C7usrNrbmPDyQCTMvmDjUtLg==,iv:clMWwt7Xk7X8/r1sq7cbdl9bqVXRcaJvFppNxBDZk5Q=,tag:byp9KYQXNMR/qro71blZ/w==,type:str]
    CODER_GITAUTH_0_CLIENT_SECRET: ENC[AES256_GCM,data:hSbISl8GYs4LHNMGmFqAtoVU4WOvpGwB7VIpxvBoJ2Bh2kNWDAS+Hu4l3Ta304uVHEqcNZDJ/IY=,iv:oYsSr6F0g3+GwAYXEaGuzQx3XHWh2Xry5lLkjc0Q6kQ=,tag:VuywconUe5s4Tii+uSh8Vw==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:tPL6zwBX1g2hWtG7QSI8l3nzeIHWpBqEhaAESw==,iv:C0snN9IR1BhhnCzQn3vifbwJ6taGWZoG7hfaEoELNnE=,tag:GhQ4aX/kEVZMUPsYXimmmQ==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:Tst9KVJ55n4DrVp0w4jI0nrR3csozLR5eWR9xfbS2AgBRhddEd+ImGWN3x3k7CrXSHLoHGH9XjM=,iv:7NKGirOsgm5zkLiCysu0L/LODQAFRhXLlTI2ZRcnsXU=,tag:zbkNyPx3vN6fiNt8mlortQ==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:J2u2rBNItkN0b0OL9OEr/JqedRr9JyJhACQ5s+Giz/qm83MYDIhVCmnn1NbZVO5TugLPZNBMdrs=,iv:BS5yxVkM6n7AyVn/9UBs+a+pCRSlM2qMSrShLMXroD4=,tag:JCrfIYP2e2fU/cBBPWh5MQ==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:i9xl/AbmPID0qCAddym7orL9cuhQ2ybrry1hGFfAfeVB8xedu2Dn3TfCVFqywCKC68lRfr4I3Av6h0TkDABB75SlC9tWNHpcGzcGZUsRsGs0rN+TdEe1UCBzsBm1kVzYP+ZJhhdDkl3D4OrE2WHU4FTLHl45C55vKo9wSp4AGkcsKp5aj9CrVU1v+wNE5ZtB8dK2Vj8s2EoG1m7bORRT9ZsD2rEjyU3/EalPyw==,iv:RKdF9TMPjqLh1owlgn+BopRU1VjtNSo/N0eiy8KoXDY=,tag:zT0jXqZuHt5vqZZO7mtiGw==,type:str]
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:wkrlLJF9apuCEVQJ/7Rv2yVsxmCchQ9U9PRe4vT2zhJPq22OxmUvbMhUbJtcIsanr8N5U8FPJv4CWw4+2CGHsYdnDaYT4g3sOa8dxi1l8Iy7kQrZHwWOWJ2mXIU8KSgkCudxUBoPCGbjbeb1FxBR+9JEGzPTXNlMixp843J3Jb0C1sdGj8LvQRwKwI0=,iv:4ZIKjC8PJHD2z0VGjljwLj1Qz8STpK7YKaV2VfY1b3w=,tag:tSGKLtv8GryOEVCwRMAE2A==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:GHyRVGCKo2Lg5SCDrXSFqIEpJz32aJ4BS5FShZ5beUoQetXUSyntprSsc2frAqMM135m1FKfN0Nd51wYIs5SUsSryt4HEvGOGSXnPY/ZHGZJ6r51eCqTpiR5Gjdd689Udl/74tvYlgThwOuoq6HNBQX+qTItnXtwgJGJdA==,iv:Qap6oAvJiJNs/f+ecBghmTEl99OaS+OzKbTEXQF9tuw=,tag:1TmnRLklnNUQxMG6DtoYsg==,type:str]
    METAL_AUTH_TOKEN: ENC[AES256_GCM,data:Ty7OKMlF5yjXiUYzuVwji2eT1tWQFDnF5FnKMh87ZeJ3xKl+necqpVjR+fk=,iv:PXcVxwCUrsUBeT7kXaZ7KNa1FBSccI5StVYa3wRzo+M=,tag:N7DLp9b8VjBxC7/P5DJAOg==,type:str]
    PDNS_API_KEY: ENC[AES256_GCM,data:mkwABFiEmItxMnaj,iv:duvHWbfOtWgzO6fVHZNLXjkJwRQ9uervPUxutVSGvi0=,tag:jsXqHp6mOmptsmhV0eMNsA==,type:str]
    PDNS_TSIG_KEY: ENC[AES256_GCM,data:H4Rc/5ClpNoT33+1vs6saBZojWnr3E5pZhB3Iy+7EfHB6TDADYCgwArameexUIjvjej7NO/QNwAqsJvE,iv:xkDoNoXXlHV/zysWqA5qPqBnUnuWDpPyawIVjBI9m1s=,tag:2Bg47wQKvS51mqsiQ6Q03w==,type:str]
    password: ENC[AES256_GCM,data:DSseXt/Ag+XferG69CsnXQ==,iv:tc2WVBgWHrPytLCG9s0smsz4pbg9DDso40RndRIhyjQ=,tag:qeaacO0LzYiFRt735nhRMg==,type:str]
    postgres-password: ENC[AES256_GCM,data:WCNMQvO26BEEyF/BNYXvLA==,iv:D2ziywTNhAFk1bHPfHe8wt9hkmfOc6Zd/UOC6rw3/6g=,tag:18Gi9ma7o2uxBKJ3SCWSgw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-07-03T10:14:22Z"
    mac: ENC[AES256_GCM,data:VuQLzobJX0p7gCMbhkzrUIN4S032UpkmoLj2x6z90IWPTFCCWija6rjT0nbZVnbWRwzhgn62dLa3U6OIG8YllkF9QJ8/WSTFM/DLr+XD8tq1OLDOPX+7eJy2QoWvASMW7l1RJrH681jtMJw6T2bLa0yl2XoDwUkqcAkeT+CpzXk=,iv:4TY9yMMB6NN6XcZPi2cIhXam2IcOKXITiCe8Qe1MseA=,tag:d3TPFDXtKN7uIDF8jRzbpQ==,type:str]
    pgp:
        - created_at: "2023-07-03T10:14:22Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA49XIfjlxQyVAQ/+O8RlAKLEb468hgB/tJT3AcWnb1mat7orWdk6UaOEby6D
            qeMCYygMts3pnsiNKzJvfI7UTt36LaF3Y+6kWjo1wlHzg6UfxQYf/xzoPDvf7m//
            ZAcG7rRj7W4mphbOUXdvmzhIqzaUI5LI91rJcRqUhiQQZd+PkzgNSb84qbV4aorG
            d2DAFQt88a3vIetWPfae+ecSkz+Q1v/X1EJdmjz/X5E25pCizE1qRXlzy/CHhQH2
            KHqPYcl9z1vMGZH84s/CBHkm/sF2MTceAvH+e+d3YtRzoB9OfG1gJD4xuWHSWOWB
            UKCSI/PXXwOKyhi6WQruZUoJ3tLuttER7z1G7vPX7oEfZv1xWTwDnIUheUnO+Nqz
            csof2EboJLens5MJZjAxSBNfSC9KqUXVV8CInOMx0nUT+wD7L7WUMw4aiPtvKdw6
            WSheuh2+1qQ6PcZ3GRUL0Xm39F5l73VhVRPSVUHjFKEbtQ0ghHjKVKhkuTTNALDk
            vdSy04l0+fIplPM5TUwZ5md7CYkXLN/cefaYjtPE5r6daw9IWW7iqXMHqXUevI6m
            2Junf+LkrHTh/74ZiWdMYLe55hQKpY9CjlB6LInKn5CLA2wMTAl0j2ohvmEA2bqN
            apaWQO/a9Z0X+mfohp2H2EI7xpxv3CHsqJEkqGL4/Ecu/t8rXcTne2/N79xZHAbU
            aAEJAhBToCMj5dTL8lavg8oIOssljM61tbaCGMN4AFuRPoA8hrTWvs1/98MdL7JJ
            bX/u90s0e+0afSts0KQoDFasEA9G832+3PKESstY5uLMpSi+/C0THxQTbcIVsWE5
            yvkiAInlsoGO
            =VS4v
            -----END PGP MESSAGE-----
          fp: 7753811D61BD7B2F83C55F3299211032AFAC5FD8
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
