---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/apps/authentik"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      LONGHORN_INGRESS_HOST: longhorn.uk.cloudnative.coop
