---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-pdns
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: cert-manager
  interval: 5m
  path: "./infrastructure/configs/cert-manager-pdns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      ACME_EMAIL: container@sharing.io
      WILDCARD_DOMAIN: container.sharing.io
      ALLOWED_ZONE: sharing.io
      ALLOWED_ZONE2: container.sharing.io
      PDNS_API_URL: https://pdns.sharing.io
      # DOMAIN: uk.sharing.io
