---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: powerdns
  namespace: flux-system
spec:
  # It does depend on at creation
  # dependsOn:
  #   - name: secrets
  interval: 5m
  path: "./infrastructure/apps/powerdns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      DNS_IP: 136.144.49.79
      DNS_DOMAIN: sharing.io
      PDNS_API_INGRESS: pdns.sharing.io
      DNSADMIN_INGRESS: powerdns.sharing.io
      SAML_URL: https://sso.sharing.io
