---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
# https://fluxcd.io/flux/components/helm/helmreleases/#specification
metadata:
  name: minio-operator
  namespace: flux-system
spec:
  targetNamespace: minio-operator
  releaseName: minio-operator
  install:
    createNamespace: true
  storageNamespace: flux-system
  maxHistory: 10
  interval: 30m
  chart:
    spec:
      chart: operator
      version: "v5.0.7" # Current as of Augst 7th, 2023
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  # https://github.com/minio/operator/blob/master/helm/operator/values.yaml
  values:
    console:
      ingress:
        enabled: true
        ingressClassName: nginx
        host: ${MINIO_INGRESS_HOST:=minio.example.com}
        tls:
          - secretName: wildcard-tls
            hosts:
              - ${MINIO_INGRESS_HOST:=minio.example.com}
      env:
        - name: CONSOLE_DEBUG_ENV
          value: "true"
    operator:
      env:
        - name: DEBUG_ENV_VAR
          value: "true"
