apiVersion: v1
data:
    CODER_GITAUTH_0_CLIENT_ID: ENC[AES256_GCM,data:TaNXqtEfwweVta7NBINUq3CYXQNwAoVI8YDV0Q==,iv:Th3ti1RO+y+nMN4y7KHAU3/8H5xudiStgdJep1kjw1o=,tag:QWcij1QwEs2eQGvcYZ/dbg==,type:str]
    CODER_GITAUTH_0_CLIENT_SECRET: ENC[AES256_GCM,data:NCLSOg86uPr4GuF8b/PGL+vmIeMj7g5E1nY2Okh5dLYZSa4i+RbKKG7DefIzTf6PWMxTn31DH9U=,iv:X0HhaVjWK/9Pal9mjXvfUc9Uc/PUCFetApZRfwAbidg=,tag:q7KUjegZ4kpSEArnnQKBRQ==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:SLosC1vYsdqSgcg3spibMwE4T6aM/CnapdspqjnKpxtBwGoowKNT7Y8BQym/BkTH1aqdNuLDLcg=,iv:G5H0KctiKhDZ3ka++y83edx19IqecKMExCbF9NedwoM=,tag:dzhsoOwhbhaMBN9PEFR4gg==,type:str]
    CODER_OAUTH2_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:fPn9bR/qfJVBwkYZwdxxdvPCRklPUApKGyT2pRYUgGtevoBd3rxm34HKtDTy0ToWLYGsx20Wy1oqfQAqYycQfU1U7Ev4/8F8CcnYDiEjLkxPydmwbjvG+PuGLAtzPVx7d6X5S07wR7huLpbJUOHQGqZ/Iy98xZD1t2VweKHJRbc2K6NeUTU9gP7ifMG3h0yxBqOfhNMJIdohq4wq8nJ+mh9dm8dQWHyNsm7PFw==,iv:sRwvjiQ0TGJrPdDkvkquGZULLHmb4gAQM/sV3ZPx0+4=,tag:VGqeaG5HY96Af+az2zpIgg==,type:str]
    CODER_OIDC_CLIENT_ID: ENC[AES256_GCM,data:9Q02uQun2A3sCDAvxEy9ybqX/9v5RGY6kFaqruVfx3YxRxt+qNWaF9KOrJW4itXhge2rTUfkkO8=,iv:CDRPxhpqAQG7BvmTAU+EFN+Ee/oadSOROnq04T6Gv4A=,tag:/Ea/2g0FNwk8X7dE4kTpww==,type:str]
    CODER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:KA+18X1EF6cbjS4Mq/EFhFt4ZEJfwrvejr6J8aCiVWx+pL1y/UjX4J3MeCKx4Sq0UpEoi6Ft6tyVQy36GsovrONyHchnrIelWNngICDuXbwTuFdqkxI2qIFB6JizKBRzF7KeRZJNjWuPyaU5NsWdatKxqvILdN3kXy2Xrzj0jXSiQ0N04u8CwOdK86LJR1z+Ts/CYweIESw4JuEx8+fF2Twwq4XV4Vri7G+4LA==,iv:VxGvQee7mKVReuZaYJKnRi2JxEuISs5LSMtsnji6oIE=,tag:3FWLtdd3F3t1wYyjKXaUdw==,type:str]
    CODER_PASSWORD: ENC[AES256_GCM,data:kBcFrV4H+ylq2giDKsLA8A==,iv:sAo70igb11dzIwTgU3pi5bsfwbR+5mlTyysWgAS4kGo=,tag:x2FD0Su00kS/s2piZuEYrg==,type:str]
    CODER_PG_CONNECTION_URL: ENC[AES256_GCM,data:Bkk8WQZMXIDcp+FFctuzMnma0Ewo9XKD2B5P0lhzqqpZLxnMgsFUisr2mjdN8L1QH7e4qKhaG5QyYwvIy5uiRBMr5/ytk4+Abf14Rd96p3t9w+xRxsqnZrC5E2buUkyZq3WWPRGG/hnwaxUJCQV5lMs9elXb5bv64QEFL6lotn5V/m74rpPnRH7bizQ=,iv:2usmtjSyeIPjQlWGyovUbv1ptTeSC0QHI/DZnqxc+m4=,tag:AGCU1O6IMsga2rcyNGV2jQ==,type:str]
    CODER_USERNAME: ENC[AES256_GCM,data:bPL7xlTkON8=,iv:GokQfjAKyy0k3mEeZ/KZNFKCoP+8wHZgLQsXPZZTue4=,tag:Mdx/VrkfE4T+x4HqJruUzw==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:n7f3B1CfytJSfbU59ajQNgdLFdXYnrhDBWHoJwKbKcchajFgH25Lu3mTpvcOCTEen5zIA+j4z6/rYH2W9dckQBHVYQ6T9Jx8Xc8nI+afREasnLmjvHrmjjndpme77FRsG75Ki0kfFpAYvMck/7uTgbv10tV01pi8hGhVWA==,iv:NxnbQydyI5ohxrWbxRolsBm9dy8hBTr2yW23j7AnbPc=,tag:aP9n6U5jNoGzaSzKaiV26g==,type:str]
    METAL_AUTH_TOKEN: ENC[AES256_GCM,data:OSlmCyWabJ7yXz5UmbKYIGZM3usqhE4w8MgpVmap68uqztqC3agB8KJqcCQ=,iv:7Ioa+aT3BXcabmbhlypwPts0iwOnlcTYkAFvjOZMk80=,tag:amkf5835mRInGcxZj35gOA==,type:str]
    PDNS_API_KEY: ENC[AES256_GCM,data:U7XelyPlodVDvtiMDYwRX/kx3KKaA3opQjodbA==,iv:h+ao+RSDmxbQrW+vMnlQYCAHyOqhK5hibnegUr0beao=,tag:zS9nbY48CzPJ3POSZAvdbw==,type:str]
    PDNS_TSIG_KEY: ENC[AES256_GCM,data:+6pBvcJwyG75O5a+Iti1BsS0w28lT5rel+qyVs4LMlVSLR5XQaEjTn8nEL91/WY1xW3Hk2ZSFvILQx9QfZ88Svqi9d3DpeniPTi2nXlHJffUBFj34vS4NIUrTIIOXPQ9KrLOxEMb1mt4j7ovs9S2IE30fBCu8vkL,iv:hlMPaF8BgbdvYAvPsQ4Da9knQYArS8bwchqZBJBretY=,tag:9Nl3bESc/92bfTvmsXn/jg==,type:str]
    TUNNELD_WIREGUARD_KEY: ENC[AES256_GCM,data:XI3OcyaTLLTwrThFDvbky5MO2ChfNyNJUOFA4ARYaYQKpJVy5MycOxmPt/KkjixCRp6/+cqMkv3VOdgY,iv:crngQ6G0P61FrzodEhRxm1Mne7rd1x7cmr4vVp2V8Qw=,tag:X3VOxkD2V9vs6yhqUQ+xpw==,type:str]
    password: ENC[AES256_GCM,data:oL9A3hdeZok3F/XE1xQufA==,iv:9dPEWofQF2jwHUTJj6qsCddWFxCImqVQtYzlcRpBu7w=,tag:E/9NK3ltbRXptihWuoob7w==,type:str]
    postgres-password: ENC[AES256_GCM,data:0yn8n4jw4WnA/kssQYjY2A==,iv:RMXJLppykeS3NkCxBqKXixrUnx8HS2Tbd6Lctbd7yhs=,tag:GVA3r8cWihyLe7z7TqcUig==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: coder
    namespace: coder
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-12T06:30:03Z"
    mac: ENC[AES256_GCM,data:DHX2BrQmp9DUoY/fYxFyTGi8M10WGh48q1yXnE5k9kIdUOKYYORwZmLT6g3rqm1Q8bMVcShHaTasPzEaWUdee0eX9d/EFJjOs/lDQT14W4pyQ2srb3X9zXfnHhquvGzbFXGH6l7o4+va0E4t6tT/c1wZ90+rR/i4Dk+nUbN/8jo=,iv:fTU3R7p/b73khrNuxumYcs6ZP2c9HH0Vh0E3hF0kMd4=,tag:o5TrMPSOrIN0Cl8BzrPo6w==,type:str]
    pgp:
        - created_at: "2023-09-12T06:30:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4DPtYQh9GOSAQ/+NpbBfr3WefZI+x2FJCNaRYpzXURCeSSRvcPRcCEytzQm
            LeazZ+x8ubadIhA9b/RxIwhu/Pdzv2h4NrccU0wnrMUigtEoJP2qtrxCf9R8GX6M
            n6LzmWhmyS1EquLlXBacOhpWuARbJOcfNCbQzrLoJBrmxuMd5bxOZL6HFh/XNQCc
            1QOZ6hkQ7B/mKxzXOZaeZbGRqoweXk4CBEiECtEmFcEq8gpwsZA1gLSWVy87nA3c
            nDk+8TaR53RDrHI+3avon+8TyfwDRIuOUL6+Lznk+JGZET1Iwijv3BbnBM/8ug7m
            XIgRLLSn2hPVIRIjiGZsk2iSRNP9OXWXgEG2gTdPDmVfTAIRehYy++m7WksMbezK
            JzdftyAD34riHYW8cxU8iHUk2UfqdOlkUhbCf2p48v+VanBN8nmrK4gfOq4f8CG7
            4fCoKSBDQieZQC8VGEIVaPkApJbH8Dx3kePsY2egUTdI0WnHvjtN82iSCYZFXIWZ
            pFnHkreGQJOco2FllJu5F0/yW739WGLTkasQU8javwVnVyf+nx9xPY0RstjjkR98
            71JkI50tqsfW1ymkt05I3yCsr55C4IC4pU5EZpbXuFa0HNPDQ/yk4asJbsMEaLy0
            be82BfP2oFs0ewM/MZ5ZUKE/0tRH6jijJ0K7M3VNb6V6VGlpZSeshF4SYxbu7/DS
            XAHBPBzWM0uN+JJ467jsTj69TDdXhAVs6HNHAb1r2UXf8fd+3l3po6Y97CVaTCti
            h+vUMVTLCJ5xOdMe80Bu6z5CXvdMoqJhVYm1AjsOwaqRFOEJuvpbqRKgG9+M
            =wNOO
            -----END PGP MESSAGE-----
          fp: F3E0675F563E84D9D952899C71A45B91E29BDA12
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
