apiVersion: v1
data:
    admin_email: ENC[AES256_GCM,data:SexyiWCVKQhlFQc3Ac8wvvhX/lapGL7F+R5zcg==,iv:7eXPUb3MHAUpG5pqRUfYZfxc0L7by5CKQ/fYgysxuG8=,tag:/TRENqqF9EyLIppaTxK0xg==,type:str]
    admin_password: ENC[AES256_GCM,data:bjNkcRjnCbEkRkuTdn+90g7Wz4mM3NKG5YXqLoWlGPc=,iv:JnB2ooUwJ+G0MCg1+SvVXFHzT3OMTkWJQ0v57lzM9GQ=,tag:rsZupD4qeigoKV1JN0lZQQ==,type:str]
    admin_user: ENC[AES256_GCM,data:uDkLU7aRj11/7ecSdz2u1aHI33WYEwRnx1ZhJQ==,iv:iQzaKg1mZeizSdsBzBkKlkPHnjCC8RyXa3dkoc15pfI=,tag:rkAYe4vfiNTFkPdb3DCnOA==,type:str]
    api_key: ENC[AES256_GCM,data:qgfVtcH/ZOQOzmqI2+vU+0pWZyuLu4iX45LE1g==,iv:csaXDokE2RfXRnvQ5TdreHhRANgzVE/R6NyOxvZq1UM=,tag:mz5OpGyeP31Lgm8uC4RA6Q==,type:str]
    postgres_password: ENC[AES256_GCM,data:L5pDd73Oxh+j/fKs2eBFBg==,iv:OoAsnu53XTxIiybl3/ber/ipemAsjeKEBls1uuRpC5M=,tag:OGEkY8yuGBZDDm2Mo9XE7g==,type:str]
    sql_url: ENC[AES256_GCM,data:ov/Fmm9ZbSuncVXT4zZCXR8/W0XN5Th5xrxPVBNUOAjI/UHVmM+RRJwIK0PFE9oTuOo84YaI5PQ4w4/Veu9W3o8VH6E+i0y1DAXcpgl7BWKM5ND6rDgZsxNnLJs=,iv:qIuTRg8eAxjGQEsREkdoCv7ZBOl/iMMBU7Bq+WkAY1Y=,tag:B5S3CHNq4iOBI6mg9MyrqA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: powerdns
    namespace: powerdns
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-09-11T12:40:36Z"
    mac: ENC[AES256_GCM,data:G9FQUWzBpNk6MyZyxb7gLnvUun5eFfwLAEfUBU67+N68L1o8/xCNHechAb27swtDPXRjD+SdvtPGne9av0c5ykvUvuimcpW8M0cgrH1CTB64yeq3iz+WTRjXvhfCeXAjQQ45deJdWV/0jmtWW9JhE6/gXSU1JEGBvLiujqO2exA=,iv:YTDYSoF5j+8+wTx9QUj6i4KdF8nvAZQzcZ759iQyrDA=,tag:vgnEFNpqn5wbtj/NNEIsYQ==,type:str]
    pgp:
        - created_at: "2023-09-11T12:40:36Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4DPtYQh9GOSAQ//ZuSopYxVDbguEHZEJ3UM2naCRcsbTQxOCU/ymBaFavkX
            mW13zgQHhEDR8P3Cf6eiHud/pmaW/oXhMjIe4LZEc+K5KgFbYx/MszHXbXf1Yv3+
            zAVttVcFb02i/mbN/sDYbBi25y80LN3zgxtyVmAFswr1j9s0GEWQVjEqC4w5YlS2
            MrRrFDWHy4zT4E2o6lDshiaaNJz7H4yy7f5qWR1iIhLuMKJnIkcz+4qUZpquLMuX
            l8NWJthpFBPUq8x8x3GbSIc+Q/IEEbDBbfaqkFs7A5vpy6lzFyUZHRvGEAcI+TF3
            hh8edrraHhHWVkhoWzuSB3mAWLTOsRgTTJue0ySYmvLYdhty8dLuTTFrnNoySoDM
            rb11Whbt5Y1LRaw0upHJZlneUYsYL1C3If8vaUboL1D5tY/67+Vgh2xIaNVL9RwN
            TclLSE2VFBkCpRw74TJ60SaLe7NBbFtWqCZCtbAapXd6KZ0xMVpPIkQK9zG9rVhK
            4eZwaO8uOt3Cd2KoX5tI0Hh1QgHSo811TyQDcprgkd0rnoP4RXNAfRf0A28prCH5
            1H5QvZHsQwfU0yBO3wJdFA/NPFyTLZ2g/0diQUPGdA0wl5rthgU8bwZCVI69s+qY
            h5HhtLwjQ+HehrWi4UBPH6pPH4W3gp4erkRgLHPF+GuIIR8GesF1KU5FHuEZV57S
            XgG3pnARAcBWpqA0Ak8H2lerdFtdhj/AjaSMh45qEqFcTH1Zdp1P3l99XB6y4zYf
            FXDL1rFgdI+IdKObze8CyKOhZs/IdENdkbXRe3sRJcclfvJBqephSNmcGZazKcY=
            =yPC3
            -----END PGP MESSAGE-----
          fp: F3E0675F563E84D9D952899C71A45B91E29BDA12
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
