---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capi
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/proliant/capi"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  # dependsOn:
  # the namespaces must exist for us to place the secrets
  # - name: namespaces
  # - name: cert-manager
  # - name: coder
