---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: secrets
  interval: 5m
  path: "./infrastructure/controllers/cert-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
  postBuild:
    substitute:
      DNS01_RECURSIVE_NAMESERVERS_ONLY: "true"
      DNS01_RECURSIVE_NAMESERVERS: 123.253.176.253:53
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 5m
  path: "./infrastructure/configs/cert-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  # https://cert-manager.io/docs/configuration/acme/dns01/
  postBuild:
    substitute:
      ACME_EMAIL: cloudnative@ii.coop
      DOMAIN: cloudnative.nz
      RFC2136_NAMESERVER: 123.253.176.253
      RFC2136_TSIG_KEYNAME: cloudnative.nz
      RFC2136_TSIG_ALGORITHM: HMACSHA256
