---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
    - name: secrets
  interval: 5m
  path: "./infrastructure/controllers/external-dns"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      EXTERNAL_DNS_PROVIDER: rfc2136
      EXTERNAL_DNS_RFC2136_HOST: 123.253.176.253
      EXTERNAL_DNS_RFC2136_ZONE: cloudnative.nz
      EXTERNAL_DNS_RFC2136_TSIG_KEYNAME: cloudnative.nz
      EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG: hmac-sha256 # hmac-sha256
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-dns
      namespace: external-dns
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: config-dns
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: external-dns
#   interval: 5m
#   path: "./infrastructure/configs/external-dns"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   postBuild:
#     substitute:
#       DOMAIN: cloudnative.nz
#       PRIMARY_DNS: ns.ii.nz
#       SECONDARY_DNS: ns2.ii.nz
#       EXTERNAL_IP: 123.253.178.101
