---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/gitops"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      GITOPS_INGRESS_HOST: gitops.cloudnative.nz
      GITOPS_USERNAME: ii
      # echo "$GITOPS_PASSWORD" | gitops get bcrypt-hash
      GITOPS_PASSWORDHASH: "$2a$10$f0rBmeTMgsziqYGJYqTOa.qsrsrvEFypbgczMFRYVV3pg8xYpWQN2"
