---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-receivier
  namespace: flux-system
spec:
  interval: 5m
  path: "./infrastructure/configs/flux-receiver"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      FLUX_RECEIVER_HOST: flux-webhook.cloudnative.nz
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/gitops"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      GITOPS_INGRESS_HOST: gitops.cloudnative.nz
      GITOPS_USERNAME: ii
      # echo "$GITOPS_PASSWORD" | gitops get bcrypt-hash
      GITOPS_PASSWORDHASH: "$2a$10$qwaBXMQdRWsabJ7w/4khOOE878zKvNbuuWbzdqxLb1VnFwMHUxUIe"
