---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops
  namespace: flux-system
  annotations:
    metadata.weave.works/description:
      This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  values:
    adminUser:
      create: true
      username: ${GITOPS_USERNAME:=admin}
      # echo "$GITOPS_PASSWORD" | gitops get bcrypt-hash
      passwordHash: ${GITOPS_PASSWORDHASH:="$2a$10$t8Yfuu9OqLsYAgvY4y81/eW7/hlSPfLkWMum67u/YGUzDzS6Vx/jm"}
