apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: sharingio-worker-a
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: sharingio
    pool: worker-a
spec:
  clusterName: sharingio
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: sharingio
      pool: worker-a
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: sharingio
        pool: worker-a
    spec:
      clusterName: sharingio
      version: v1.27.3
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: sharingio-worker-a
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: PacketMachineTemplate
        name: sharingio-worker-a
