---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: ingress-nginx
spec:
  secretName: wildcard-tls
  dnsNames:
    - "*.${DOMAIN:=ii.nz}"
    - "${DOMAIN:=ii.nz}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
