apiVersion: v1
data:
    clientID: ENC[AES256_GCM,data:4nj5XTHdkP/IZViqj7gG1LM96KpKH3ByC0t80soGokEC8fJwd/20V8sKavzWrTAXL2PUivKRF9A=,iv:VrhxOr7mrR4MaODZkNzpuVDJbWQEtelSTv0nFjiB+eY=,tag:NAJNm3bZE1mSpjuR/i1vOg==,type:str]
    clientSecret: ENC[AES256_GCM,data:0fiQYNVo4jFftrGULsR1RqrrAREP4/S1ez7aXwRBDuNkZFXg5kPvi6W/yKWCokzGcLVG24GJoGdlTrybu93SwBq+8n+qvh3F7JEY4r6GBegfKxThXn5Me1R8T4pMNDW/IUk9YWRY1L7yP/dkOGWstsEB5l7tuJzVDTeVAgXChJyaXCu6g9eloNgz2dfBtPKe2i2kVqR+9ETSHGOda4chLTc/qesbCmPaSeE5Ow==,iv:5Jc5cplJzGQ75sgGtdJWQcQ8W2fai1lJMpZeUlwTTOQ=,tag:3PiKv4I2OYtrO8WAt7mPyA==,type:str]
    issuerURL: ENC[AES256_GCM,data:OmuKlt4gTzXvz8zFTJXCC4Z3wmCIaKJANiqC/P41Nke/mTUnd4e/MXJ+RTPZawoLOf5+RyhHnn8AI9U0QzC3Ww==,iv:WVUx026pDFRWr7uovBrRRt0H3LtEci8zfU4Ob8ZBYV8=,tag:4zYmjJaJNQ7NzxCQQX8zUg==,type:str]
    redirectURL: ENC[AES256_GCM,data:YG87gDlKZ2NzkPlN/SVwv/kldIfhDcm8zYi/RHXhOVEm0lsTBi0ZVo2mT338X0e5uU5AUJ6ty64iTxNG,iv:Fu0tb+TkrAGtxLuTyppI5XURvNsAWeX+kYVN4BkU7t4=,tag:yZAA7tF8KMtIjcUwHsauaw==,type:str]
    tokenDuration: ENC[AES256_GCM,data:5NXDAJ9CxFc=,iv:Pu+B6JhiJzz8epBHYtIxJjg6iNe0tHd9QTqBRdxrNEM=,tag:m8N/OEC4LCrmns24ChkURg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: oidc-auth
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-29T12:41:37Z"
    mac: ENC[AES256_GCM,data:OX+IqZ1iW8RWDc3IzS6rwaHg1z6MWimFpIJy4aFq4+QN/Exdtdy2Qa/S6Iw0UlAo5M3ieBRqTR2v8TyL6iLQ5C8MOXJlRp47R420kqp7RJ10SnwpyK/FTsB0i43MRSIH8T+F9y6Odtf1VF9vEYkEIU49K11+ZqwZ9PWIIrcA/hg=,iv:rITXASEoRTJ3aoT6rQ/iN7CpfpTCR0qZZH2587XxP4c=,tag:kkgzKD9FYQ4Lvta7T7/jAw==,type:str]
    pgp:
        - created_at: "2023-08-29T12:41:37Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5yBPHua1+foAQ//Tn6esItYC0N8/2wIFsTY7P7oY4avhRobDPtIKgk33F9k
            5frP+7mUZC0qEGpbM2cHql9k96/v5g2QJRzPHX9qma7FnlNgw76JzrPUaLJxxmAJ
            STAxiV70Dxd/fh2SdATFquuB1yvZOgKeMRt3HQZFR0c4oC5Mj8dkC5Hwlf1dg5VX
            1uwGPzR2CVfjih9xXaJdf32OwVbzb3Ye11UYO/hkG9crJ1jbnJD/STwRzEf8wmIH
            yNrAKant75Iv3Ga2+ZHrmc68CaZP6P4zxAtmxl6V2QXDyoqhwhN3+QjS+xcTa7uX
            iNB0hZC2RqCPzALGXL5M/BD2BdAku3lDAHG9LMSFvD9XPMFc82E2mihy3GiAkKQU
            YO7ozCOPvWmY3uejgj9E3GlZRG5WB5JpOSQGyPbYP3Y+4OHeFs+5HAeQlmmcG/KN
            MHMIk3nKXcRA1mbKf2MTuGk+eiFOZbKExz10JRwjMe8jlIkYgCKtP/f6JuysBRbI
            YoMWFA//LUPnekMXUdS+ACKoMi3mdG3m44F89eftjMtfnz8XFGvIVSDBa9z9a/bj
            xBDcav3LLE4TCwE4SfVRC+zlEnRLn2lqpIQBqM4lSMOPonp5sMa+WaTu92ubyrde
            mUz3gi+2IJUk3/54pM4f9MQeapQZEOP8ePibFQCwrfGxuN4ZyzFda40Oqvz+DI7U
            aAEJAhDeYnJupEGwAtAKH7QYIL90owqw03qFzUl5cgKhR7F5H4LOF4Om6xltudtn
            /CwXmaOtzCCOER7/1HKW3+dNtcpMmwui7WKRMzgmeaqw2IJotdfU6QMwDb5KifjZ
            ulqXYOB7P8qM
            =iJBr
            -----END PGP MESSAGE-----
          fp: 6CFB156EEFE7417E2567D5FD37732CFA004DC229
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
