---
apiVersion: v1
kind: Service
metadata:
  name: iiamabby-auditsink
spec:
  ports:
    - name: http
      port: 9900
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: auditlogger
    app.kubernetes.io/name: auditlogger
  type: ClusterIP
